import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopBar from "./components/topbar";
import Footer from "./components/footer"
import Banner from "./components/banner"
import EdutecHero from "./components/herosection";
import ContactForm from "./components/ContactForm";
import Testimonials from "./components/testmonial";
import BottomUpper from "./components/bottomupper";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TopBar />
        <Banner/>
        <EdutecHero />
        {children}
        <BottomUpper/>
        <Testimonials/>
        <ContactForm/>
        <Footer />
      </body>
    </html>
  );
}
